### ISSUE TITLE
Add some thresholds in sensor display

### ISSUE THREAD

**Issue by Rodov** [5e/streamdeck-hwinfo-plugin#31] opened 2024-10-31 15:23 UTC
Need some (possible two) thresholds (normal, average and high)(maybe, gradient colours too... ) to display sensor colour.
Can you add this feature, please?

**Comment by 5e** [comment] 2024-11-01 00:58
Duplicate of https://github.com/5e/streamdeck-hwinfo-plugin/issues/29

**Closed by 5e** 2024-11-01 00:58 UTC
